# Generated by Django 6.0 on 2026-03-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
