# Generated by Django 6.0.2 on 2026-03-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
