# Generated by Django 6.0 on 2026-03-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cotisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('verse', 'Versé'), ('non_verse', 'Non versé')], default='non_verse', max_length=100)),
                ('cycle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='core.cycle')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='core.membre')),
            ],
        ),
    ]
